### ISSUE TITLE
Combine with ORS Tools?

### ISSUE THREAD

**Issue by Saijin-Naib** [nilsnolde/pelias-qgis-plugin#6]
Have you ever considered combining Pelias Geocoding QGIS plugin with the ORS Tools plugin?

There's a lot of overlap between the two, and having the tools combined into the one Processing Plugin would be amazing for automating geocoding with Model Builder, etc.

Thanks for the great tools (and services!)

**Comment by nilsnolde** [comment]
I wonder why the *** Github doesn't notify the owner of repos by default.. 

Sorry @Saijin-Naib, wasn't intentional. Would be great to combine some of them. However, before I'd combine those two (most work actually in GUI stuff, not that serious work you're right), I'd prefer to combine this with any other geocoding API plugin that's out there. Then combine ORS Tools with all the other routing API plugins. And finally merge all those together to create one to rule them all.

Haha but that's a dream I can't tackle all by myself. Smth like that would have to be done entirely from scratch with a good OOM, which none of the plugins (shame on myself here) currently have. But it's been on my mind quite a lot. I think if I can get the basis done, other people could chime in. 

However, that's what I thought with our [`routing-py`](https://github.com/gis-ops/routing-py) library as well. So far exactly 0 contributions.. A little discouraging..

**Comment by Saijin-Naib** [comment]
I'm sorry to hear that.

I wish you much luck with future work, and thanks again for the tools!
